config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user_profiles, only: [:show, :new, :create]



  resources :orders, only: [:show, :new, :create] do
    member do
      get 'recommendations'
    end
  end


  resources :products, only: [:show]

  resources :profiles, only: [:show]

  root to: 'pages#home'

  # get "/recommandations", to: "orders#recommended"
  get "/lastbasket", to: "orders#last"
  get "/profile", to: "profiles#show"
  get "/dashboard", to: "profiles#dashboard"
  get "/orders", to: "orders#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_card_bottom.html.erb
<% @order.products.each do |product| %>
<div class="card-bottom">
  <div class="row">
    <div class="col-4">Type</div>
    <div class="col-5"><%= product.pnns_group_2 %></div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
  </div>
  <div class="row">
    <div class="col-4">Nutri-score</div>
    <div class="col-5">
      <% if product.nutrition_grades_tags != "unknown" %>
      <%= image_tag "#{product.nutrition_grades_tags}-nutriscore.png", class: "nutriscore-img" %>
      <% end %>
      </div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
  </div>
  <div class="row">
    <div class="col-4">Additives</div>
    <div class="col-5"><%= JSON.parse(product.additives_tags).count %>
    </div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
  </div>
  <div class="row">
    <div class="col-4">Packaging</div>
    <div class="col-5"><% JSON.parse(product.packaging_tags).each do |add| %>
      <%= add.gsub('-', " ") %>
      <% end %>
      </div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
  </div>
  <div class="row">
    <div class="col-4">Origin</div>
    <div class="col-5"><%= product.countries_tags %></div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
  </div>
  <div class="row">
    <div class="col-4">Labels</div>
    <div class="col-5">
      <% JSON.parse(product.labels_tags).each do |add| %>
        <% if add.match("agriculture")%>
          <%= image_tag "label_bio.png", class: "label-bio-img"%>
        <% end %>
        <% if add.match("fair")%>
          <%= image_tag "fairtrade.png", class: "label-fair-img"%>
        <% end %>
      <% end %>
    </div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
    <div class="col-1">a</div>
  </div>
</div>
<% end %>

app/views/shared/_card_top.html.erb
<% Order.last.products.each do |product| %>

  <h1><%= product.generic_name_fr %></h1>
  <img src="<%= product.image_front_url %>" alt="<%= product.generic_name_fr %>">
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# if params[:controller] == 'orders' && ['show', 'last', 'recommendations'].include?(params[:action]) %>
  <div class="footer">
    <div class="footer-links">
      <div class="footer-left">
        <%= link_to lastbasket_path, class: "#{'active' if params[:action] == 'last'}" do %>
          <i class="fas fa-shopping-basket"></i></a>
        <% end %>

        <%= link_to orders_path, class: "#{'active' if params[:controller] == 'orders' && ["index", "show"].include?(params[:action])}" do %>
          <i class="fas fa-history"></i>
        <% end %>
      </div>

      <div class="footer-center">
        <% if @order && @order.persisted? %>
          <% if params[:action] == "recommendations" %>
            <% magic_button_path = current_user.orders.last == @order ? lastbasket_path : order_path(@order) %>
          <% else %>
            <% magic_button_path = recommendations_order_path(@order) %>
          <% end %>
        <%end %>
        <%= link_to magic_button_path, class: "#{'active' if params[:action] == 'recommendations'} #{'magic-gray' unless params[:controller] == 'orders' && ['show', 'last', 'recommendations'].include?(params[:action])}", id: "magic-btn" do %>
          <i class="fas fa-magic footer-toggle"></i>
        <% end %>
      </div>

      <div class="footer-right">
        <%= link_to dashboard_path, class: "#{'active' if params[:action] == 'dashboard'}" do %>
          <i class="fas fa-tachometer-alt tachometer"></i>
        <% end %>

         <%= link_to profile_path(:id), class: "#{'active' if params[:controller] == 'profiles' && params[:action] == 'show'}" do %>
          <i class="fas fa-user-circle"></i></a>
        <% end %>
      </div>
    </div>
  </div>

<%# else %>
<!--   <div class="footer">
    <div class="footer-links">

      <%#= link_to lastbasket_path, class: "#{'active' if params[:action] == 'last'}" do %>
        <i class="fas fa-shopping-basket"></i></a>
      <%# end %>

      <%#= link_to orders_path, class: "#{'active' if params[:controller] == 'orders' && ["index", "show"].include?(params[:action])}" do %>
        <i class="fas fa-history"></i>
      <%# end %>

      <%#= link_to dashboard_path, class: "#{'active' if params[:action] == 'dashboard'}" do %>
        <i class="fas fa-tachometer-alt tachometer"></i>
      <%# end %>

       <%#= link_to profile_path(:id), class: "#{'active' if params[:controller] == 'profiles' && params[:action] == 'show'}" do %>
        <i class="fas fa-user-circle"></i></a>
      <%# end %>

    </div>
  </div> -->

<%# end %>

app/views/shared/_navbar.html.erb
<!-- <div class="row navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%#= link_to dashboard_path, class: "navbar-brand" do %>
  <i class="fas fa-tachometer-alt tachometer"></i>
  <% #end %>

  <h1>GLOBULE</h1>

  <div class="navbar-toggler-position">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fas fa-user-alt"></span>
    </button>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown text-right">
        <%#= link_to "Profile", profile_path(:id), class: "dropdown-item text-secondary pl-0" %>
        <%#= link_to "Log in", new_user_session_path, class: "dropdown-item text-secondary pl-0" unless user_signed_in? %>
        <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item text-secondary" if user_signed_in? %>
      </li>
    </ul>
  </div>
</div>
 -->